---
- name: Deploying minecraft bedrock server
  hosts: all
  become: yes
  roles:
    - ansible_get_docker
    - mc_bedrock_server_deploy
  environment:
    MC_VERSION: "{{ MC_VERSION }}"
  tags: deploy

- name: Updating minecraft bedrock server
  hosts: all
  become: yes
  roles:
    - mc_bedrock_server_update
  environment:
    MC_VERSION: "{{ MC_VERSION }}"
  tags: update

- name: Halting minecraft bedrock server
  hosts: all
  become: yes
  tasks:
    - name: Stopping game container
      docker_container:
        name: bedrock-server
        state: absent
  tags: halt

