---
- name: Deploy minecraft bedrock server
  hosts: all
  become: yes
  roles:
    - ansible_get_docker
    - mc_bedrock_server_deploy
  environment:
    MC_VERSION: "{{ MC_VERSION }}"
  tags: deploy

- name: Update minecraft bedrock server
  hosts: all
  become: yes
  roles:
    - mc_bedrock_server_update
  environment:
    MC_VERSION: "{{ MC_VERSION }}"
  tags: update

