Vagrant.configure("2") do |config|
  config.vm.synced_folder "/root/vagrant_projects/keys", "/keys"
  config.vm.provision "shell", inline: "cat /keys/ansible_key.pub >> /home/vagrant/.ssh/authorized_keys"

  # Define CentOS7 for minecraft bedrock server
  config.vm.define "mc_centos7" do |mc|
    config.vm.hostname = "mc-centos7"
    mc.vm.box = "generic/centos7"
    mc.vm.network "private_network", ip: "10.0.4.254"
    mc.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
  end
end