Vagrant.configure("2") do |config|
  config.vm.synced_folder "/root/vagrant_projects/keys", "/keys"
  config.vm.provision "shell", inline: "cat /keys/ansible_key.pub >> /home/vagrant/.ssh/authorized_keys"

  # Define CentOS7 for minecraft bedrock server
  config.vm.define "centos7_mc" do |centos7|
    config.vm.hostname = "centos7_mc"
    centos7.vm.box = "generic/centos7"
    centos7.vm.network "private_network", ip: "10.0.4.254"
    centos7.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
        v.gui = false
    end
  end