---
# tasks file for mc_bedrock_server_deploy
- name: create mc server directory
  file:
    path: "{{ service_path }}/backup/{{ item }}"
    state: directory
  loop:
    - "update_backup"
    - "daily_backup"

- name: template conf files
  copy:
    src: '../../../docker-compose.yml'
    dest: "{{ service_path }}/docker-compose.yml"
    

- name: change python interpreter to python3
  set_fact:
    ansible_python_interpreter: /usr/bin/python3
  when: centos7 is defined

- name: stop the (existing) mc bedrock server
  docker_compose:
    project_src: "{{service_path}}"
    state: absent
  ignore_errors: true

- name: run new mc bedrock server
  docker_compose:
    project_src: "{{service_path}}"
    pull: yes
    build: yes
    state: present