---
# tasks file for mc_bedrock_server_deploy
- name: creating mc server directory
  file:
    path: "{{ service_path }}/backup/{{ item }}"
    state: directory
  loop:
    - "update_backup"
    - "daily_backup"
    - "weekly_backup"

- name: Copying conf files
  copy:
    src: '../../../docker-compose.yml'
    dest: "{{ service_path }}/docker-compose.yml"

- name: Copying backup script
  copy:
    src: '../files/backup_server.sh'
    dest: "{{ service_path }}/backup/"
    mode: 0744

- name: changing python interpreter to python3
  set_fact:
    ansible_python_interpreter: /usr/bin/python3
  when: centos7 is defined

- name: stopping the (existing) mc bedrock server
  docker_compose:
    project_src: "{{service_path}}"
    state: absent
  ignore_errors: true

- name: Making sure no container named bedrock-server exists
  docker_container:
    name: bedrock-server
    state: absent

- name: running new mc bedrock server
  docker_compose:
    project_src: "{{service_path}}"
    pull: yes
    state: present

- name: Add backup script to crontab
  cron:
    name: "Backup bedrock server data"
    minute: "10"
    hour: "4"
    job: "{{ service_path }}/backup/backup_server.sh {{ service_path }}/backup"
    state: present